# See https://wiki.hyprland.org/Configuring/Monitors/
# ----------------------------------------------------- 
# Monitor Configuration
# ----------------------------------------------------- 

# Your primary G24F 2 monitor
# Rule: monitor = name, resolution, position, scale
monitor=DP-3, 1920x1080@144, 0x0, 1

# Fallback rule (Auto-detect anything else)
monitor = , preferred, auto, 1
